export const LAY_DANH_SACH_PHONG_VE = "LAY_DANH_SACH_PHONG_VE";
export const CHON_GHE = "CHON_GHE";
export const DAT_VE_DONE = "DAT_VE_DONE";
export const TAB_ACTIVE = "TAB_ACTIVE";
export const LAY_DS_GHE_USER_KHAC_DANG_CHON = "LAY_DS_GHE_USER_KHAC_DANG_CHON";
