const GET_CAROUSEL = "GET_CAROUSEL";
const LAY_DANH_SACH_PHIM = "LAY_DANH_SACH_PHIM";
const OPEN_MODAL_YOUTUBE = "OPEN_MODAL_YOUTUBE";

export { GET_CAROUSEL, LAY_DANH_SACH_PHIM, OPEN_MODAL_YOUTUBE };
